// src/components/ui/empty-state.tsx
import { cn } from '@/lib/utils';
import { Button } from './button';

interface EmptyStateProps {
  icon?: React.ReactNode;
  title: string;
  description?: string;
  action?: {
    label: string;
    onClick?: () => void;
    href?: string;
  };
  className?: string;
}

export function EmptyState({ icon, title, description, action, className }: EmptyStateProps) {
  return (
    <div
      className={cn(
        'flex flex-col items-center justify-center rounded-lg border border-dashed p-8 text-center animate-in fade-in-50',
        className
      )}
    >
      {icon && <div className="mb-4 text-muted-foreground">{icon}</div>}
      <h3 className="mb-1 text-lg font-semibold">{title}</h3>
      {description && <p className="mb-4 text-sm text-muted-foreground max-w-sm">{description}</p>}
      {action && (
        <Button onClick={action.onClick} asChild={!!action.href}>
          {action.href ? <a href={action.href}>{action.label}</a> : action.label}
        </Button>
      )}
    </div>
  );
}

// apps/web/src/components/EmptyState.vue
<script setup lang="ts">
import { Button } from '@juanie/ui'
import type { Component } from 'vue'

interface Props {
  icon?: Component
  title: string
  description?: string
  actionLabel?: string
  actionIcon?: Component
}

const props = defineProps<Props>()

const emit = defineEmits<{
  action: []
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-12 px-4 text-center">
    <component
      v-if="icon"
      :is="icon"
      class="h-16 w-16 text-muted-foreground mb-4"
    />
    <h3 class="text-lg font-semibold mb-2">{{ title }}</h3>
    <p v-if="description" class="text-sm text-muted-foreground max-w-md mb-6">
      {{ description }}
    </p>
    <Button v-if="actionLabel" @click="emit('action')">
      <component v-if="actionIcon" :is="actionIcon" class="mr-2 h-4 w-4" />
      {{ actionLabel }}
    </Button>
  </div>
</template>
